export const AppImages = {
    app_logo : require('../assets/Images/logo.png'),
    mosq : require('../assets/Images/mosque1.png'),
    drop_icon : require('../assets/Images/dropIcon.png'),
    right_arrow: require('../assets/Images/Vector.png'),
    left_arrow: require('../assets/Images/Group.png'),
    notification: require('../assets/Images/notification.png'),
    lock: require('../assets/Images/lock.png'),
    mobile: require('../assets/Images/mobile.png'),
    human: require('../assets/Images/human.png'),
    qr: require('../assets/Images/qr.png'),
    home: require('../assets/Images/home.png'),
    quesionMark: require('../assets/Images/questionMark.png'),
    bell: require('../assets/Images/bell.png'),
    drawerIcon: require('../assets/Images/drawerIcon.png'),
    search: require('../assets/Images/search.png'),
    qrCode: require('../assets/Images/qrCode.png'),
    rightArrow: require('../assets/Images/rightArrow.png'),
    mask: require('../assets/Images/mask.png'),
    checkbox: require('../assets/Images/checkbox.png'),
    rightWhiteArrow: require('../assets/Images/rightWhiteArrow.png'),
    helpImage: require('../assets/Images/helpImage.png'),
    mosq: require('../assets/Images/mosq.png'),
    leftWhiteArrow: require('../assets/Images/leftWhiteArrow.png'),
    mosque: require('../assets/Images/mosque1.png'),
    address: require('../assets/Images/address.png'),
    profileImage: require('../assets/Images/profileImage.png'),
    multiBooking: require('../assets/Images/multiBooking.png'),
    lightQrCode: require('../assets/Images/lightQrCode.png'),
    Language: require('../assets/Images/Language.png'),
    inviteOthers: require('../assets/Images/inviteOthers.png'),
    writeToUs: require('../assets/Images/writeToUs.png'),
    logout: require('../assets/Images/logout.png'),
}